### ISSUE TITLE
Need test files for the 4000 scopes

### ISSUE THREAD

**Issue by scottprahl** [Cat-Ion/rigol-ds4000-wfm#1]
Your work inspired me to adapt all the existing Rigol formats to kaitai struct format [RigolWFM](https://github.com/scottprahl/RigolWFM).  

However, don't have a 4000 series scope and need `.wfm` files (along with the `.csv` and `.txt` header file info) to validate the parsing.  Perhaps you can help by adding such test files to your repository or to just leave a zip file in a comment on mine.  

Thanks

**Comment by Cat-Ion** [comment]
I'm really happy to hear that you found it useful!

I don't think I have any files at the moment, but I'll try to make some later
this evening. Would it help to have more than one waveform, or is one set of
wfm/csv/txt files for the calibration waveform sufficient?

**Comment by scottprahl** [comment]
Ideally 2 sets of files (could be the same signal but with different vertical and horizontal scales and offsets).  However, one set would allow me to at least verify basic functionality.

**Comment by Cat-Ion** [comment]
Here you go! Took me a bit because I had to get a compatible flash drive first :) 
[rigol-ds4024.tar.gz](https://github.com/Cat-Ion/rigol-ds4000-wfm/files/4238063/rigol-ds4024.tar.gz)

**Comment by scottprahl** [comment]
thanks! I will let you know how it goes.

**Comment by scottprahl** [comment]
@Cat-Ion, thanks for your help.  I just released a working parser at 

https://github.com/scottprahl/RigolWFM

(Note that this is a new repository.) I will close this issue now.

I will close this
